{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nrKubernetesOtel.ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: '13133'
    alb.ingress.kubernetes.io/healthcheck-path: /health/status
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /health/status
        pathType: Prefix
        backend:
          service:
            name: {{ include "nrKubernetesOtel.service.fullname" . }}
            port:
              number: 13133
      - path: /v1/logs
        pathType: Prefix
        backend:
          service:
            name: {{ include "nrKubernetesOtel.service.fullname" . }}
            port:
              number: 4318
      - backend:
          service:
            name: {{ include "nrKubernetesOtel.service.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
{{- end }}
