{{- if .Values.ingress.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpointslices-reader-binding
  namespace: pipeline-control
subjects:
  - kind: User
    name: EKS-Dev:EKSGetTokenAuth
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: endpointslices-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}