{{- $licenseKey := include "newrelic.common.license._licenseKey" . -}}
{{- $secretName := include "newrelic.common.license.secretName" . -}}
{{- $secretKeyName := include "newrelic.common.license.secretKeyName" . -}}

{{- if and $licenseKey $secretName $secretKeyName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
data:
  {{ $secretKeyName }}: {{ $licenseKey | b64enc }}
{{- end }}