apiVersion: v1
kind: Service
metadata:
  name: {{ include "nrKubernetesOtel.service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: nr-http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    {{- include "newrelic.common.labels.selectorLabels" . | nindent 4 }}
    component: deployment
  internalTrafficPolicy: Cluster