apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pipeline-control
  name: endpointslices-reader
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list"]