name: Release Charts

on:
  push:
    branches:
      - main
      - gateway-charts

jobs:
  validate-gh-pages-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download remote index file and check equality
        run: |
          curl -vsSL https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml > index.yaml.remote
          LOCAL="$(md5sum < index.yaml)"
          REMOTE="$(md5sum < index.yaml.remote)"
          echo "$LOCAL" = "$REMOTE"
          test "$LOCAL" = "$REMOTE"

  release:
    runs-on: ubuntu-latest
    #needs: [ validate-gh-pages-index ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
